### PR TITLE
Fix win inst

### PR DESCRIPTION
**Pull request by bkidwell**
Windows build process changes:
* Cleaned up build README a lot.
* Cleaned up build process a lot.
* Added "README for Zim for Windows" file -- it's in your Start Menu / Zim Desktop Wiki folder.
  * README mentions where you can find your Plugins folder!
* Removed dependency on PortableApps.com for the portable launcher and portable packaging.
* Created our own standalone NSIS-based portable and DEBUG MODE launchers (see new README in ./windows/src).
* Removed requirement for build person to download "Microsoft.VC90.CRT" folder; found it in %WINDOWS%\WinSxS.
* Created Python script that runs the desktop installer builder.
* Prepared to merge Portable installer with Desktop installer (one package); it's not done yet; for now we're shipping a Zip file for the Portable version.

Still yet to be done on the Windows build process:
* Integrate missing Spell Check files into the package so the plugin works.
* See if Windows clipboard access is still a problem and investigate and fix.
* Test on several versions of Windows

### CODE REVIEW

**Comment by jaap-karssenberg** [comment]
I'll try to rebase these changes into a single patch on top of the current master.

**Comment by jaap-karssenberg** [comment]
@bkidwell Would the following merge message describe the changes you made?

    Windows build process changed
    
    Cleaned up build process and documentation:
    - Removed dependency on PortableApps.com for the portable launcher and portable packaging.
    - Created our own standalone NSIS-based portable and DEBUG MODE launchers (see new README in ./windows/src).
    - Removed requirement for build person to download "Microsoft.VC90.CRT" folder; found it in %WINDOWS%\WinSxS.
    - Exclude Tcl and Tkinter from py2exe build
    - Created Python script that runs the desktop installer builder.
    - README mentions where you can find your Plugins folder!
    - Added "README for Zim for Windows" file -- it's in your Start Menu / Zim Desktop Wiki folder.

**Comment by bkidwell** [comment]
Yes @jaap-karssenberg that comment to summarize this merge is fine.

**Comment by jaap-karssenberg** [comment]
Committed as e01471313b550ee25f1358ec2782e361b614ab0b

**Pull request closed without merging**
